---

- name: combine eip filter
  set_fact:
    _aws_vpc_nat_eip_filter: |
      {{
        aws_vpc_nat_eip_filter_additional + natgw.eip_filter
      }}

- name: gather eip facts by filter
  ec2_eip_facts:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') | default(omit) }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') | default(omit)  }}"
    security_token: "{{ lookup('env', 'AWS_SECURITY_TOKEN') | default(omit) }}"
    profile: "{{ aws_vpc_nat_profile | default(omit) }}"
    region: "{{ natgw.region | default(aws_vpc_nat_default_region) }}"
    filters: "{{ _aws_vpc_nat_eip_filter | get_attr('key', 'val') }}"
  register: _aws_eip_facts

- name: fail if no eip was found
  assert:
    that:
      - _aws_eip_facts.addresses is defined
      - _aws_eip_facts.addresses | length == 1
    msg: Not exactly one eip has been found

- name: set eip id and name
  set_fact:
    _aws_eip_id: "{{ _aws_eip_facts.addresses[0].allocation_id }}"
    _aws_eip_ip: "{{ _aws_eip_facts.addresses[0].public_ip }}"
